version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    restart: always

  app:
    image: php:apache
    volumes:
      - ./app:/var/www/html
    depends_on:
      - api
    restart: always
  proxy:
    build: proxy
    depends_on:
      - api
      - app
    restart: always
    ports:
      - 80:80
